### ISSUE TITLE
No longer working since patch 5.35

### ISSUE THREAD

**Issue by Pandahoro** [tesu/PennyPincher#2]
as title says, it runs /penny help brings up help menu, but does not copy 1 lower to clipboard anymore

**Comment by tesu** [comment]
PennyPincher will break after every update due to opcodes being reshuffled. The opcodes are generally updated pretty quickly, you can see the PR for 5.35 here: https://github.com/goatcorp/DalamudAssets/pull/1
After opcodes are updated, restarting should get you the new opcodes and PennyPincher will work again. If you don't get an update on restart, you can delete `%appdata%\xivlauncher\addon` to force a redownload.
