### ISSUE TITLE
When FFXIV gives you empty results, it still copies a value

### ISSUE THREAD

**Issue by zandzpider** [tesu/PennyPincher#25]
![image](https://user-images.githubusercontent.com/321691/165816434-53e174dd-9c75-4e87-96ba-fa91735c0e7e.png)

**Comment by zandzpider** [comment]
These are 3 empty results in succession, and it pulls out a number (from cache?)
Nothing should be done if there are no results (this is a bug from FF, since there are actual items in the list)

**Comment by tesu** [comment]
Thanks for flagging this. I'm not sure if I can fix this - the plugin inspects network messages to determine what the prices are (there's no cache involved), and in the case of this "rate-limiting" error, the network messages are still sent. The messages are also strange; I think the first page of results gets skipped over when you encounter the error, which is why you get a slightly higher price copied.

**Comment by zandzpider** [comment]
Interesting. 
Always wanted to look into the network aspect of this. I'll clone it and fiddle (don't count on anything tho)

**Comment by zandzpider** [comment]
https://github.com/tesu/PennyPincher/pull/26

**Comment by zandzpider** [comment]
This PR should fix this issue
https://github.com/tesu/PennyPincher/pull/27
